name: Sync TOP500_WHITE_AD.conf from SR-Rule

on:
  schedule:
    - cron: '0 21 * * *'  # Runs daily at 5 AM HKT (9 PM UTC)
  workflow_dispatch:  # Enables manual trigger from GitHub UI

jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenClash-Rule repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download rule file from SR-Rule
        run: |
          curl -L https://raw.githubusercontent.com/pandit-psw/SR-Rule/main/TOP500_WHITE_AD.conf -o TOP500_WHITE_AD.conf

      - name: Commit and push changes if updated
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          if ! git diff --quiet TOP500_WHITE_AD.conf; then
            git add TOP500_WHITE_AD.conf
            git commit -m "Auto-sync TOP500_WHITE_AD.conf from SR-Rule"
            git push
          else
            echo "No changes detected."
