name: Update Config

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      - name: Make changes (example - replace with your actual changes)
        run: |
          # Assuming you have a file named TOP500_WHITE_AD.conf that you are modifying
          # Example:
          echo "Updated content" > TOP500_WHITE_AD.conf
          git add TOP500_WHITE_AD.conf
          git commit -m "Update TOP500_WHITE_AD.conf from pandit-psw/SR-Rule"
      - name: Push changes to OpenClash-Rule repository
        run: |
          git remote add target "https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/pandit-psw/OpenClash-Rule.git"
          git push target HEAD:SR-Rule
